custom:
  writeEnvVars: ${file(../authentication/env.yml)}

service: serverless-authentication-test-token # NOTE: update this with your service name

provider:
  name: aws
  stage: ${self:custom.writeEnvVars.STAGE}
  region: ${self:custom.writeEnvVars.REGION}
  runtime: nodejs4.3

functions:
  testToken:
    handler: handler.test
    events:
      - http:
          path: test-token
          method: get
          cors: true
          integration: lambda
          authorizer:
            arn: arn:aws:lambda:${self:provider.region}:${self:custom.writeEnvVars.AWS_ACCOUNT_ID}:function:${self:custom.writeEnvVars.SERVICE_NAME}-${self:provider.stage}-authorize
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
