service: serverless-authentication-test-token # NOTE: update this with your service name

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs4.3

functions:
  testToken:
    handler: handler.test
    events:
      - http:
          path: test-token
          method: get
          cors: true
          integration: lambda
          authorizer:
            arn: arn:aws:lambda:us-east-1:AWS-ACCOUNT-ID:function:serverless-authentication-${self:provider.stage}-authorize
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            identityValidationExpression: .*
